/**
 * CSRF Protection Middleware
 *
 * This module provides Cross-Site Request Forgery (CSRF) protection for the MNNR
 * platform using the **double-submit cookie pattern** with HMAC signatures.
 *
 * **What is CSRF?**
 * CSRF attacks trick authenticated users into executing unwanted actions on a
 * web application. For example, transferring funds, changing email addresses,
 * or deleting data without their knowledge.
 *
 * **Protection Strategy:**
 * This module implements CSRF protection through:
 * 1. **Token Generation:** Cryptographically secure random tokens with HMAC signatures
 * 2. **Double-Submit Pattern:** Token sent in both header and validated on server
 * 3. **HMAC Verification:** Ensures token integrity and prevents tampering
 * 4. **Method-Based Protection:** Only validates state-changing operations (POST, PUT, DELETE, PATCH)
 *
 * **Security Properties:**
 * - Tokens are 32 bytes (256 bits) of cryptographically secure randomness
 * - HMAC-SHA256 signature prevents token forgery
 * - Automatic verification on all state-changing requests
 * - Exempt paths for webhooks (which use signature-based auth)
 *
 * @module lib/csrf
 * @security Critical security component
 *
 * @example
 * ```typescript
 * // In API route
 * import { csrfProtection } from '@/lib/csrf';
 *
 * export async function POST(request: NextRequest) {
 *   // Check CSRF token
 *   const csrfError = await csrfProtection(request);
 *   if (csrfError) {
 *     return csrfError; // Returns 403 if invalid
 *   }
 *
 *   // Process request safely
 *   const result = await processRequest(request);
 *   return NextResponse.json(result);
 * }
 * ```
 *
 * @example
 * ```typescript
 * // In client-side code
 * // 1. Get CSRF token from server response header
 * const response = await fetch('/api/some-endpoint');
 * const csrfToken = response.headers.get('X-CSRF-Token');
 *
 * // 2. Include token in subsequent requests
 * await fetch('/api/create-resource', {
 *   method: 'POST',
 *   headers: {
 *     'Content-Type': 'application/json',
 *     'X-CSRF-Token': csrfToken
 *   },
 *   body: JSON.stringify(data)
 * });
 * ```
 */

import { NextRequest, NextResponse } from "next/server";
import { createHmac, randomBytes } from "crypto";

/**
 * CSRF secret key for HMAC signatures
 *
 * **IMPORTANT:** Set CSRF_SECRET environment variable in production!
 * The secret is used to sign and verify CSRF tokens, preventing forgery.
 *
 * @security Store this in environment variables, never in code
 * @private
 */
const CSRF_SECRET = process.env.CSRF_SECRET || "default-csrf-secret-change-in-production";

/**
 * Length of the random token portion (in bytes)
 * 32 bytes = 256 bits of entropy = 64 hex characters
 *
 * @constant
 * @private
 */
const CSRF_TOKEN_LENGTH = 32;

/**
 * Generate a cryptographically secure CSRF token
 *
 * Creates a CSRF token using the following format:
 * `{random_token}.{hmac_signature}`
 *
 * **Token Structure:**
 * - **Random Token:** 32 bytes (256 bits) of cryptographically secure random data
 * - **HMAC Signature:** SHA-256 HMAC of the random token using CSRF_SECRET
 * - **Format:** `{64_hex_chars}.{64_hex_chars}`
 *
 * **Security Properties:**
 * - Unpredictable: Uses crypto.randomBytes (CSPRNG)
 * - Tamper-proof: HMAC signature prevents modification
 * - Verifiable: Signature can be validated server-side
 * - Stateless: No database storage required
 *
 * @returns {string} CSRF token in format: `token.signature`
 *
 * @example
 * ```typescript
 * // Generate a new CSRF token
 * const token = generateCsrfToken();
 * console.log(token);
 * // Output: "a1b2c3d4...64chars.e5f6g7h8...64chars"
 * ```
 *
 * @example
 * ```typescript
 * // Use in API route to provide token to client
 * export async function GET() {
 *   const response = NextResponse.json({ message: 'Hello' });
 *   const csrfToken = generateCsrfToken();
 *   response.headers.set('X-CSRF-Token', csrfToken);
 *   return response;
 * }
 * ```
 */
export function generateCsrfToken(): string {
  const token = randomBytes(CSRF_TOKEN_LENGTH).toString("hex");
  const signature = createHmac("sha256", CSRF_SECRET)
    .update(token)
    .digest("hex");

  return `${token}.${signature}`;
}

/**
 * Verify a CSRF token's authenticity
 *
 * Validates that a CSRF token:
 * 1. Has the correct format (token.signature)
 * 2. Has a valid HMAC signature
 * 3. Was generated by this server (signature matches)
 *
 * **Validation Process:**
 * 1. Split token into random part and signature
 * 2. Recompute HMAC signature from random part
 * 3. Compare recomputed signature with provided signature
 * 4. Return true only if they match exactly
 *
 * @param {string} token - The CSRF token to verify (format: `token.signature`)
 * @returns {boolean} `true` if token is valid, `false` otherwise
 *
 * @example
 * ```typescript
 * const token = generateCsrfToken();
 * const isValid = verifyCsrfToken(token);
 * console.log(isValid); // true
 *
 * const tampered = token + 'abc';
 * const isValidTampered = verifyCsrfToken(tampered);
 * console.log(isValidTampered); // false
 * ```
 *
 * @example
 * ```typescript
 * // Verify token from client request
 * const clientToken = request.headers.get('X-CSRF-Token');
 * if (!verifyCsrfToken(clientToken)) {
 *   return new Response('Invalid CSRF token', { status: 403 });
 * }
 * ```
 */
export function verifyCsrfToken(token: string): boolean {
  try {
    const [tokenPart, signature] = token.split(".");

    if (!tokenPart || !signature) {
      return false;
    }

    const expectedSignature = createHmac("sha256", CSRF_SECRET)
      .update(tokenPart)
      .digest("hex");

    return signature === expectedSignature;
  } catch (error) {
    return false;
  }
}

/**
 * CSRF Protection Middleware for Next.js API Routes
 *
 * Automatically validates CSRF tokens for state-changing HTTP methods.
 * This middleware should be called at the beginning of API route handlers
 * that perform mutations (create, update, delete operations).
 *
 * **Protected Methods:**
 * - POST (create operations)
 * - PUT (update operations)
 * - DELETE (delete operations)
 * - PATCH (partial update operations)
 *
 * **Exempted Methods:**
 * - GET (read operations, safe by definition)
 * - HEAD (metadata requests)
 * - OPTIONS (CORS preflight requests)
 *
 * **Exempted Paths:**
 * - `/api/webhooks/*` (use signature-based authentication instead)
 *
 * **Token Location:**
 * The middleware looks for the CSRF token in the following request headers:
 * - `X-CSRF-Token` (case-sensitive)
 * - `x-csrf-token` (case-insensitive fallback)
 *
 * @param {NextRequest} request - The incoming Next.js request object
 * @returns {Promise<NextResponse | null>} Error response if CSRF check fails, null if passes
 *
 * @example
 * ```typescript
 * // Protect a POST endpoint
 * export async function POST(request: NextRequest) {
 *   // Validate CSRF token
 *   const csrfError = await csrfProtection(request);
 *   if (csrfError) {
 *     return csrfError; // Returns 403 Forbidden
 *   }
 *
 *   // Safe to process the request
 *   const body = await request.json();
 *   const result = await createResource(body);
 *   return NextResponse.json(result);
 * }
 * ```
 *
 * @example
 * ```typescript
 * // Protect a DELETE endpoint
 * export async function DELETE(
 *   request: NextRequest,
 *   { params }: { params: { id: string } }
 * ) {
 *   const csrfError = await csrfProtection(request);
 *   if (csrfError) return csrfError;
 *
 *   await deleteResource(params.id);
 *   return NextResponse.json({ success: true });
 * }
 * ```
 *
 * @example
 * ```typescript
 * // GET requests pass through automatically
 * export async function GET(request: NextRequest) {
 *   // No CSRF check needed for GET
 *   const data = await fetchData();
 *   return NextResponse.json(data);
 * }
 * ```
 */
export async function csrfProtection(
  request: NextRequest
): Promise<NextResponse | null> {
  // Skip CSRF check for safe methods (read-only operations)
  if (["GET", "HEAD", "OPTIONS"].includes(request.method)) {
    return null;
  }

  // Skip CSRF check for webhooks (they use signature-based authentication)
  // Webhooks from Stripe, etc. are authenticated via signing secrets
  if (request.nextUrl.pathname.startsWith("/api/webhooks")) {
    return null;
  }

  // Get CSRF token from request headers
  const csrfToken =
    request.headers.get("x-csrf-token") ||
    request.headers.get("X-CSRF-Token");

  // Reject if no token provided
  if (!csrfToken) {
    return NextResponse.json(
      {
        error: "CSRF token missing",
        message: "CSRF token is required for this operation",
      },
      { status: 403 }
    );
  }

  // Verify token authenticity
  if (!verifyCsrfToken(csrfToken)) {
    return NextResponse.json(
      {
        error: "Invalid CSRF token",
        message: "CSRF token validation failed",
      },
      { status: 403 }
    );
  }

  // CSRF check passed
  return null;
}

/**
 * Add a CSRF token to a response
 *
 * Generates a new CSRF token and adds it to the response headers.
 * Clients should extract this token and include it in subsequent
 * state-changing requests.
 *
 * **Usage Pattern:**
 * 1. Server generates token and sends in response header
 * 2. Client stores token (in memory, localStorage, or state)
 * 3. Client includes token in X-CSRF-Token header for POST/PUT/DELETE/PATCH
 * 4. Server validates token using csrfProtection middleware
 *
 * @param {NextResponse} response - The Next.js response object to modify
 * @returns {NextResponse} The response with CSRF token header added
 *
 * @example
 * ```typescript
 * // Add CSRF token to API response
 * export async function GET() {
 *   const data = { message: 'Hello' };
 *   let response = NextResponse.json(data);
 *
 *   // Add CSRF token to headers
 *   response = addCsrfTokenToResponse(response);
 *
 *   return response;
 * }
 * ```
 *
 * @example
 * ```typescript
 * // Client-side: Extract and use the token
 * const response = await fetch('/api/data');
 * const csrfToken = response.headers.get('X-CSRF-Token');
 *
 * // Store for later use
 * sessionStorage.setItem('csrfToken', csrfToken);
 *
 * // Use in subsequent requests
 * await fetch('/api/create', {
 *   method: 'POST',
 *   headers: {
 *     'Content-Type': 'application/json',
 *     'X-CSRF-Token': csrfToken
 *   },
 *   body: JSON.stringify(data)
 * });
 * ```
 */
export function addCsrfTokenToResponse(response: NextResponse): NextResponse {
  const token = generateCsrfToken();
  response.headers.set("X-CSRF-Token", token);
  return response;
}
